### ISSUE TITLE
[screenrec] Video Saver broken [must be fixed]

### ISSUE THREAD

**Issue by ninety9090** [EntySec/ghost#190]
![help](https://user-images.githubusercontent.com/72395726/96361774-2ecfd280-115b-11eb-8f5d-5ec8a930d7a0.png)

**Comment by ninety9090** [comment]
the file did not appear in the Desktop. Thanks in Advance

**Comment by enty8080** [comment]
@ninety9090 Looks like it's broken, but I will not fix this because I do not want to update Ghost Framework anymore.

People who contributed to this repository, maybe they want to fix this:

@jaxparrow07 @AXIM0S @game-lover

**Comment by ninety9090** [comment]
Okay thanks for creating this framework. I hope people contributed in that repository can fix the bug. God bless mor power to come

**Comment by ninety9090** [comment]
> @ninety9090 Looks like it's broken, but I will not fix this because I do not want to update Ghost Framework anymore.
> 
> People who contributed to this repository, maybe they want to fix this:
> 
> @jaxparrow07 @AXIM0S @game-lover

hi, suddenly it works now but the problem now is the video you record is not saving in the desktop but the image appears.

**Comment by ninety9090** [comment]
Thanks you for updating. I hope someone can fix this bug.

**Comment by ninety9090** [comment]
I think that this is the final update about this bug. While cleaning the storage of my phone i saw a video of what im doing in may screen, so to finalize my conclusion i tried to execute again the screenrec command, after that i figure out that the video of my recordings will save in my phone storage. I hope someone figure out how to fix it. Thankyou in advance.

**Comment by jaxparrow07** [comment]
> I think that this is the final update about this bug. While cleaning the storage of my phone i saw a video of what im doing in my screen, so to finalize my conclusion i tried to execute again the screenrec command, after that i figure out that the video of my recordings will save in my phone storage. I hope someone figure out how to fix it. Thankyou in advance.

Yeah! The problem occurs when it tries to `pull` the file from the target ( your device ). The recording will be saved and It will be pulled once the recording is stopped. You can use the `download` option to get the screen recording manually if you can't see it in your device. `download /sdcard/screen.mp4 <target location ( in your pc )>` in the ghost framework to download the file. I hope this will help you.

**Comment by enty8080** [comment]
> > I think that this is the final update about this bug. While cleaning the storage of my phone i saw a video of what im doing in my screen, so to finalize my conclusion i tried to execute again the screenrec command, after that i figure out that the video of my recordings will save in my phone storage. I hope someone figure out how to fix it. Thankyou in advance.
> 
> Yeah! The problem occurs when it tries to `pull` the file from the target ( your device ). The recording will be saved and It will be pulled once the recording is stopped. You can use the `download` option to get the screen recording manually if you can't see it in your device. `download /sdcard/screen.mp4 <target location ( in your pc )>` in the ghost framework to download the file. I hope this will help you.

If you want you can make a PR.

**Comment by jaxparrow07** [comment]
> > > I think that this is the final update about this bug. While cleaning the storage of my phone i saw a video of what im doing in my screen, so to finalize my conclusion i tried to execute again the screenrec command, after that i figure out that the video of my recordings will save in my phone storage. I hope someone figure out how to fix it. Thankyou in advance.
> > 
> > 
> > Yeah! The problem occurs when it tries to `pull` the file from the target ( your device ). The recording will be saved and It will be pulled once the recording is stopped. You can use the `download` option to get the screen recording manually if you can't see it in your device. `download /sdcard/screen.mp4 <target location ( in your pc )>` in the ghost framework to download the file. I hope this will help you.
> 
> If you want you can make a PR.

I am so happy to help a big such framework that I used to learn new things!

**Comment by ninety9090** [comment]
thank you for your help. I will try what you said.

**Comment by ninety9090** [comment]
> > > I think that this is the final update about this bug. While cleaning the storage of my phone i saw a video of what im doing in my screen, so to finalize my conclusion i tried to execute again the screenrec command, after that i figure out that the video of my recordings will save in my phone storage. I hope someone figure out how to fix it. Thankyou in advance.
> > 
> > 
> > Yeah! The problem occurs when it tries to `pull` the file from the target ( your device ). The recording will be saved and It will be pulled once the recording is stopped. You can use the `download` option to get the screen recording manually if you can't see it in your device. `download /sdcard/screen.mp4 <target location ( in your pc )>` in the ghost framework to download the file. I hope this will help you.
> 
> If you want you can make a PR.

how?? Im just a newbie here and want to learn more and someday I want to contribute too. Thanks for noticing of this bug. God bless

**Comment by ninety9090** [comment]
> /sdcard/screen.mp4

Its great the issue are now fixed thanks for the help mr. jaxparrow and enty.

**Comment by jaxparrow07** [comment]
> how?? Im just a newbie here and want to learn more and someday I want to contribute too. Thanks for noticing of this bug. God bless
Create a fork, Clone it to your PC, Make changes (Add features, fix bugs ), Push (changes that you made to your repo), Create a pull request, so enty can merge it... Search the internet if you have anymore doubts.

**Comment by ninety9090** [comment]
> > how?? Im just a newbie here and want to learn more and someday I want to contribute too. Thanks for noticing of this bug. God bless
> 
> Create a fork, Clone it to your PC, Make changes (Add features, fix bugs ), Push (changes that you made to your repo), Create a pull request, so enty can merge it... Search the internet if you have anymore doubts.

Okay sir jaxparrow i will do my best to contribute or to fix bugs in ghost framework. Im happy because I think that you pull me up to improve and learn something.

**Comment by enty8080** [comment]
@jaxparrow07 Do you have twitter account?

**Comment by jaxparrow07** [comment]
> @jaxparrow07 Do you have twitter account?

Yeah! I created a new account @Jaxparrow2. This is my Twitter ID. I use Discord often, Discord tag **Jaxparrow#1797**. I followed you and sent a message.

**Comment by enty8080** [comment]
@jaxparrow07 @ninety9090 We moved to @EntySec, this is our new home.

**Comment by enty8080** [comment]
Removed `screenrec` command because I do not want it to exist.
