### ISSUE TITLE
Traceback (most recent call last) KEYCODE

### ISSUE THREAD

**Issue by karton1606** [EntySec/ghost#193]
I can't use keycode with any number. Log: 
keycode 22
Traceback (most recent call last):
  File "./ghost", line 575, in <module>
    main()
  File "./ghost", line 269, in main
    nums = open("substrate/keynums.txt").read()
FileNotFoundError: [Errno 2] No such file or directory: 'substrate/keynums.txt'

**Comment by karton1606** [comment]
![image](https://user-images.githubusercontent.com/73573052/97391821-201eb380-18f1-11eb-85c9-c8e38b874eda.png)
And i have question: function screen don't work? Sorry for bad eng...

**Comment by enty8080** [comment]
@karton1606 `screen` here #190, but your problem with `keycode` fixed now.
