### ISSUE TITLE
Now i get this KEYCODE

### ISSUE THREAD

**Issue by karton1606** [EntySec/ghost#194]
![image](https://user-images.githubusercontent.com/73573052/97413164-7e5c8e00-1913-11eb-8996-deb84ebeb052.png)
Log: keycode 22
[-] Keycode is not found!
ghost(178.207)> keycode 2
chmod: cannot access 'data/kaycode/keycode.sh': No such file or directory
ghost(178.207)> keycode 2
chmod: cannot access 'data/kaycode/keycode.sh': No such file or directory
ghost(178.207)> keycode 82
[-] Keycode is not found!

**Comment by enty8080** [comment]
I fixed error with `chmod`. Maybe key code 22 not not available.

**Comment by enty8080** [comment]
@karton1606 Everything fixed now
