### ISSUE TITLE
![Screenshot_2020-10-04_11-55-08](https://user-images.githubusercontent.com/72139567/95020334-7d984b00-0638-11eb-8d74-199104ed560a.png)

### ISSUE THREAD

**Issue by stark2226** [EntySec/ghost#196]
![Screenshot_2020-10-04_11-55-08](https://user-images.githubusercontent.com/72139567/95020334-7d984b00-0638-11eb-8d74-199104ed560a.png)
need help

_Originally posted by @baibhav470 in https://github.com/EntySec/ghost/issues/65#issuecomment-703275544_

**Comment by enty8080** [comment]
#112

**Comment by SkyJoim** [comment]
https://github.com/EntySec/ghost/issues/196#issue-738495345

**Comment by SkyJoim** [comment]
git clone https://github.com/EntySec/ghost/issues/196#issue-738495345
