### ISSUE TITLE
error opening ghost framework 

### ISSUE THREAD

**Issue by junkpole** [EntySec/ghost#198]
I am getting the following error when I am trying to open it and I am using kali Linux on a virtual machine.

Traceback (most recent call last):
  File "./ghost", line 37, in <module>
    from core.ghostcat import GhostCat
  File "/root/ghost/core/ghostcat.py", line 32, in <module>
    from core.ghost import ghost
  File "/root/ghost/core/ghost.py", line 32, in <module>
    from core.transfer import transfer
ModuleNotFoundError: No module named 'core.transfer'

**Comment by jaykali** [comment]
Lots of guys having this issue.. Solve it please

**Comment by enty8080** [comment]
Have you installed it with `install.sh`?

**Comment by enty8080** [comment]
@junkpole This fixed now. Reinstall

**Comment by junkpole** [comment]
![Uploading 60F55C4B-7B11-44D4-931C-812565361C25.png…]()
