### ISSUE TITLE
Problem running on MAC / [-] Failed to connect to "IP":5555!

### ISSUE THREAD

**Issue by behar21** [EntySec/ghost#199]
I tried running different IP and also tried it with my own devices, I know the port (I see it in my device) but it is giving me always the same result
<img width="390" alt="Screen Shot 2020-11-19 at 12 38 33 PM" src="https://user-images.githubusercontent.com/5995618/99661774-9f248900-2a64-11eb-8368-9e6b9116908a.png">

**Comment by enty8080** [comment]
Install `adb`, `brew install adb`
