### ISSUE TITLE
[unknown] core.transfer: module not found

### ISSUE THREAD

**Issue by DakshIndustries** [EntySec/ghost#201]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by niksimCpp** [comment]
@DakshIndustries Please fill the form and said me what steps you did before facing this error. I can't understand what you meant.

**Comment by enty8080** [comment]
@DakshIndustries I fixed this bug.
