### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by scr44tch** [EntySec/ghost#202]
im running latest Kali Linux in virtualbox
i tried to connect to my phone:

Connecting to xx.xx.xx.xx
Failed to connect to xx.xx.xx.xx

i tried multiple phones, all have usb debugging enabled,
also tried some ip from shodan but i cant connect to any of them,
adb is installed on kali

Host OS: Linux Mint 19
virtualbox 6.1
kali-linux-2020-4-vbox-amd64
Ghost Framework v6.0
adb --version                                            
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-8
Installed as /usr/lib/android-sdk/platform-tools/adb

**Comment by sim0nov** [comment]
@scr44tch 

Is this is your local device or your device from here?: 
* https://www.shodan.io/search?query=android+debug+bridge

**Comment by scr44tch** [comment]
i tried my own devices local 192.xx.xx.xx 
phones are online
also tried ip's from shodan

same result

**Comment by sim0nov** [comment]
Please send me your phone model and Android release version.

**Comment by scr44tch** [comment]
Samsung Galaxy S9 Android 10
Samsung Galaxy S7 Android 8

**Comment by sim0nov** [comment]
@scr44tch Ok. Try running this:

```
adb start-server; adb connect <your_ip>
```

and send me output.

**Comment by scr44tch** [comment]
$ adb start-server; adb connect 192.xxx.xx.xx
* daemon not running; starting now at tcp:5037
* daemon started successfully
unable to connect to 192.xxx.xx.xx:5555: No route to host

**Comment by sim0nov** [comment]
@scr44tch Thats it. If you can see your phone's IP address is unreachable. This is not a Ghost Framework issue.

**Comment by sim0nov** [comment]
@scr44tch You can try this solution: 

* https://stackoverflow.com/questions/33462720/adb-unable-to-connect-to-192-168-1-105555

**Comment by scr44tch** [comment]
sry for reviving this issue but im a bit confused,

i managed to get access to one of my phones and my shield tv, 
but only after i connected my phone via usb and authorized the connection.

on my authorized desktop:
ghost> set rhost 192.168.1.12
[i] RHOST ==> 192.168.1.12
ghost> run
[*] Connecting to 192.168.1.12:5555...
ghost(192.168.1.12:5555)> 

on my pi (not authorized):
ghost> set rhost 192.168.1.12
[i] RHOST ==> 192.168.1.12
ghost> run
[*] Connecting to 192.168.1.12:5555...
[-] Failed to connect to 192.168.1.12:5555!

my pi is on the same switch, same network as my desktop

isnt the ghost framework supposed to get me access to the device without the authorization?
or did i get that wrong?
