### ISSUE TITLE
Unrecognized command: connect/disconnect

### ISSUE THREAD

**Issue by seltec** [EntySec/ghost#203]
**Describe the bug**
After many installations [around 7/8 with new download and uninstall] i have always the same issue. I can start the ghost framework but can not connect a device.
The system is temporarily running on Kali 2020.4 as live distribution. It was also tested on Windows in a VM with the same result.

Ghost Framework was installed via ./install.sh

**Screenshots**
![Screenshot 2020-11-22 11:29:25](https://user-images.githubusercontent.com/73937514/99902483-14d36380-2cb6-11eb-8539-539b1b571f2e.png)

**Desktop (please complete the following information):**
 - Kali Linux 2020.4 [live]
 - Ghost Framework v6.0

Maybe someone can help.

**Comment by enty8080** [comment]
@seltec Yes I changed this. You should set `RHOST` to target host and run `run`.
