### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by UjjwalDeep** [EntySec/ghost#205]
It says failed to connect even when the host is up and it's tcp 5555  port is open
Failed to connect
![IMG_20201124_164437](https://user-images.githubusercontent.com/68703963/100087481-ce783300-2e74-11eb-9f42-d87bf7693653.jpg)
 Nmap proof that host is up and tcp 5555 port is open.
![IMG_20201124_164500](https://user-images.githubusercontent.com/68703963/100087642-0aab9380-2e75-11eb-8106-2e2446066f53.jpg)

Please don't close this issue before providing a solution.

**Comment by enty8080** [comment]
@UjjwalDeep Looks like you are using Virtual machine. So that means that there is no connection over NAT. #202

**Comment by legend14333** [comment]
same bro unable to connect

**Comment by legend14333** [comment]
i think this nw version of ghost framework dosent support to connect i think
