### ISSUE TITLE
[bug] libreadline-dev not found

### ISSUE THREAD

**Issue by BillyEvGreece** [EntySec/ghost#207]
> ghost

```
Traceback (most recent call last):
  File "/root/.ghost/./ghost", line 33, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Comment by BillyEvGreece** [comment]
i tried :  pip3 install gnureadline
 and it says

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/gnureadline/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/gnureadline/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/gnureadline/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/gnureadline/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/gnureadline/
Could not fetch URL https://pypi.org/simple/gnureadline/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/gnureadline/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement gnureadline (from versions: none)
ERROR: No matching distribution found for gnureadline
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
                                                                         

Sorry for bothering i am new i dont know what to do if you have time pls help

**Comment by BillyEvGreece** [comment]
i also tried pip install gnureadline and after the installation when i type sudo ghost or ghost the issue on the top happens again

Traceback (most recent call last):
File "/root/.ghost/./ghost", line 33, in
import readline
ModuleNotFoundError: No module named 'readline'

**Comment by enty8080** [comment]
@BillyEvGreece Try this:

```
sudo apt-get install readline
```

**Comment by enty8080** [comment]
@BillyEvGreece Type your OS please

**Comment by BillyEvGreece** [comment]
thank for your time and help but the problem remains :[
![image](https://user-images.githubusercontent.com/67794074/100528226-01a72300-31e3-11eb-8d47-370c6287972c.png)

the same issue occures when i try the command sudo pip3 install readline

**Comment by BillyEvGreece** [comment]
after a lot of search and tries i found that video which basically shown me how to download again python in the correct way 
https://www.youtube.com/watch?v=pHXkVbxULfI&ab_channel=PhantomBD  [or at least that i understand ] 
i am writing this down in order if another beginner like me comes across the same issue to be able to find the solution easily without having to search for hours like i did .
Thank you @enty8080 for your time and help i really appreciate it 👍 .
