### ISSUE TITLE
Access public ip in ghost

### ISSUE THREAD

**Issue by ricko2991** [EntySec/ghost#210]
Hi, its not related to ghost, I just want to get an answer. You can close this issue because it is not related to ghost tool.

I did not find anyone who is an expert in ADB so I asked in here, maybe here I can get help. as far as I test ghost using my Android, yes I can log into ADB using my local ip for example 192.168.1.12. I can also connect to ADB if I do port forwading on my router. But the problem here is I use a sim card. So what I want here is how can I open my public port if i use sim card on my phone? so I can connect to ADB or ghost tool?

As a far i see, shodan has a lot of public hosts and it makes me wonder, are they opening their hosts to the public via the router or sim card they use?

Thanks :)

**Comment by enty8080** [comment]
@ricko2991 

I do not know answer because I am not an Android developer. Try asking this question on Android Devs Forum.
