### ISSUE TITLE
Failed to connect to target!

### ISSUE THREAD

**Issue by Adamcey** [EntySec/ghost#211]
Upon using the run command on version 6, it return errors message 'Failed to connect to target!'.
i.e ghost> run 149.34............
[-] Failed to connect to target!

Regards

**Comment by enty8080** [comment]
@Adamcey Run 
```
adb connect <ip>
```

and if it returns `failed to connect` close issue because this is an adb issue.

NEXT TIME USE ISSUE TEMPLATE OR I'LL CLOSE ISSUE AUTOMATICALLY!
