### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by MrBastaki** [EntySec/ghost#214]
the IP which been used in these two commands are from
https://www.shodan.io/search?query=Android+Debug+Bridge

ghost> set RHOST 59.16.169.190
[i] RHOST ==> 59.16.169.190
ghost> run 59.16.169.190
[*] Connecting to 59.16.169.190:5555...
[-] Failed to connect to 59.16.169.190:5555!
ghost> set RHOST 119.236.119.55
[i] RHOST ==> 119.236.119.55
ghost> run 119.236.119.55
[*] Connecting to 119.236.119.55:5555...
[-] Failed to connect to 119.236.119.55:5555!

but as you can see they are still failing to connect

**Comment by enty8080** [comment]
#211

**Comment by MrBastaki** [comment]
thank you sir i will try
