### ISSUE TITLE
Failed to connect to

### ISSUE THREAD

**Issue by JosephCordero** [EntySec/ghost#216]
****Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:**
1. Go to 'git clone https://github.com/EntySec/ghost'
(Continued part 1) 
cd ghost
chmod +x install.sh
./install.sh
2. Enter "ghost" everything loads.
3. Typed in "options
4. Then did "set RHOST <IP address>"
5. Typed "run" after 
6. Connecting to: ###.###.###.##
(Continued part 6)
Failed to connect to:###.###.###.##

**Expected behavior**
Honestly, I'm probably doing something wrong I just can't figure it out.

**Screenshots**

![image](https://user-images.githubusercontent.com/54633753/103195893-27dae400-48b1-11eb-857b-1ac08adf7327.png)

****Desktop (please complete the following information):**
 - OS: Kali Linux on Windows 10
 - Version [e.g. 22]**

**Smartphone (please complete the following information):**

**Additional context**
I'm trying to learn new Tools/Scripts so I have a better knowledge of them if I have problems down the line

**Comment by king5300** [comment]
Hunter

**Comment by king5300** [comment]
> ****Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:**
> 1. Go to 'git clone https://github.com/EntySec/ghost'
> (Continued part 1) 
> cd ghost
> chmod +x install.sh
> ./install.sh
> 2. Enter "ghost" everything loads.
> 3. Typed in "options
> 4. Then did "set RHOST <IP address>"
> 5. Typed "run" after 
> 6. Connecting to: ###.###.###.##
> (Continued part 6)
> Failed to connect to:###.###.###.##
> 
> **Expected behavior**
> Honestly, I'm probably doing something wrong I just can't figure it out.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> ![image](https://user-images.githubusercontent.com/54633753/103195893-27dae400-48b1-11eb-857b-1ac08adf7327.png)
> 
> ****Desktop (please complete the following information):**
>  - OS: Kali Linux on Windows 10
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]**
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. iPhone6]
>  - OS: [e.g. iOS8.1]
>  - Browser [e.g. stock browser, safari]
>  - Version [e.g. 22]
> 
> **Additional context**
> I'm trying to learn new Tools/Scripts so I have a better knowledge of them if I have problems down the line
> https://www.shodan.io/host/47.111.75.233

**Comment by king5300** [comment]
[]()

**Comment by king5300** [comment]
Hunh

**Comment by king5300** [comment]
Hhu

**Comment by game-lover** [comment]
[#112](112)

**Comment by JosephCordero** [comment]
> Hunter

what?

**Comment by JosephCordero** [comment]
> [#112](112

**Comment by JosephCordero** [comment]
> [#112](112)

I tried my phone to see if it would work and it didn't but I'll check #112 out
