### ISSUE TITLE
helper.check_adb_installation() 

### ISSUE THREAD

**Issue by amenforthy** [EntySec/ghost#225]
Hi, This May Be The Greatest Project i have came across in the 2020 year and i love it honestly.
I just wanted to tell you about a syntax error i found in the main **ghost** script that calls some  scripts in  the directory **core**
which is not correctly calling the **check_adb_installation**   (you forget to type the parentheses ) method that check if adb is installed (which is needed for your framework) from the helper class.

P.S. this is my first time submitting a bug ( i don't think this is bug) so take it easy on me and i don't know if that syntax error was left as is intentionally.

**Comment by enty8080** [comment]
Hi, @amenforthy 

Thanks for submitting this bug. Yeah I know that Ghost Framework contains a lot of bugs now and I going to fix them all soon.

I am now working on [ZetaSploit Framework](https://github.com/EntySec/ZetaSploit) and it took all my free time.

You can fix this `check_adb_installation()` bug and submit Pull Request with patch for it.

**Comment by enty8080** [comment]
@amenforthy Bug fixed, thanks.
