### ISSUE TITLE
missing connect and disconnect options

### ISSUE THREAD

**Issue by redcurse** [EntySec/ghost#226]
after install ghost framework  and try to connect to an ip it says it can't + when i use help i can't find the connect option or the disconnect
`ghost> help

Core Commands
=============

    Command        Description
    -------        -----------
    clear          Clear terminal window.
    exit           Exit Ghost Framework.
    help           Show available commands.
    options        Show available options.
    run            Run Ghost Framework.
    set            Set an option value.
`

**Comment by enty8080** [comment]
@redcurse 

```
show options
```

then

```
set <option> <value>
run
```

**Comment by redcurse** [comment]
still same problem `ghost> show options
[-] Unrecognized command!
`

**Comment by redcurse** [comment]
> @redcurse
> 
> ```
> show options
> ```
> 
> then
> 
> ```
> set <option> <value>
> run
> ```
still same problem
` ghost> show options [
-] Unrecognized command!
`

**Comment by redcurse** [comment]
> @redcurse
> 
> ```
> show options
> ```
> 
> then
> 
> ```
> set <option> <value>
> run
> ```

still the connect options not show up can u explain plz !!!

**Comment by Manavpate166** [comment]
same problrm bro

**Comment by enty8080** [comment]
@Manavpate166 @redcurse 

Guys!

I said you should

```
set RHOST <target_ip>
run
```
