### ISSUE TITLE
shell.check_root() // ghost.is_root()

### ISSUE THREAD

**Issue by brkncookie** [EntySec/ghost#227]
Hey Again Hope you're fine, i just wanted to ask you why are you having in the **shell.py** script a ``check_root`` method that always returns ``False`` ? and more than that you're implementing it in your **shell.py 's**  **if statments**  and because of that even if the device is rooted it will always ``return False``  which will always return the message ``Target device is not rooted!`` i don't understand why you did that.
i suggest you reuse the ``is_root`` method in the **core/ghost.py** to get correct results if the device is rooted and thus correct result for your **shell.py 's**  **if statments** 

P.S. in the last issue i opened i wanted to offer you help about the ghost framework documentation (inside the code and outside it) but i forgot :^) it will be an honor to me if you accept my help.

**Comment by enty8080** [comment]
@amenforthy Because it `todo`

**Comment by jaxparrow07** [comment]
That feature is implemented... 👍

**Comment by jaxparrow07** [comment]
> Hey Again Hope you're fine, i just wanted to ask you why are you having in the **shell.py** script a `check_root` method that always returns `False` ? and more than that you're implementing it in your **shell.py 's** **if statments** and because of that even if the device is rooted it will always `return False` which will always return the message `Target device is not rooted!` i don't understand why you did that.
> i suggest you reuse the `is_root` method in the **core/ghost.py** to get correct results if the device is rooted and thus correct result for your **shell.py 's** **if statments**
> 
> P.S. in the last issue i opened i wanted to offer you help about the ghost framework documentation (inside the code and outside it) but i forgot :^) it will be an honor to me if you accept my help.
Also, it will work for only the host system. The checkroot won't work on adb.
