### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by filecomfritas** [EntySec/ghost#229]
when I finish the installation and try to run the framework I'm getting this message of error:

┌──(root💀kali)-[/home/kali/Downloads/ghost-main]
└─# ghost
Traceback (most recent call last):
  File "/root/.ghost/./ghost", line 33, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by enty8080** [comment]
#50
