### ISSUE TITLE
in ghost framwork6 i cant see the connect , disconnect comands 

### ISSUE THREAD

**Issue by mahmoud20107** [EntySec/ghost#230]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mahmoud20107** [comment]
https://fastupload.co/1083359

**Comment by enty8080** [comment]
#226

**Comment by mahmoud20107** [comment]
Thanks a lot bro
