### ISSUE TITLE
ghost When you try it turns me this error

### ISSUE THREAD

**Issue by Sebultura2** [EntySec/ghost#244]
Traceback (most recent call last):
  File "/root/.ghost/./ghost", line 36, in <module>
    from core.badges import badges
ModuleNotFoundError: No module named 'core.badges'

**Comment by Juan8922** [comment]
Try to use: pip install badges.

**Comment by thecakeisfalse** [comment]
Reinstall ghost

**Comment by robert4js** [comment]
Hi I tried installing many times 
still the error is  
File "/root/.ghost/./ghost", line 36, in
from core.badges import badges
ModuleNotFoundError: No module named 'core.badges'

Please Help

**Comment by thecakeisfalse** [comment]
What python version do you use?

**Comment by enty8080** [comment]
Hello, @robert4js, @thecakeisfalse

Thanks for reporting this problem, now I am ready to help you solve it.
A lot of issues here, like this one, connected with that the components of Ghost Framework could not be found by main handler.

I added python3 interpreter declaration to all of Ghost Framework components including main handler and core modules, so you should not worry about your python version.

```python3
#!/usr/bin/env python3
```

My solution is very simple - just check your python3 interpreter installation and if your other python environment is set for python >= 3.8.

```shell
$ apt-get update
$ apt-get upgrade # skip if you are running the lastest version of your OS
$ apt-get install -y python3 python3-dev python3-pip
```

Also it will be great if you check that `/usr/bin/env` exists and if it is not an empty file.

```shell
$ file /usr/bin/env
/usr/bin/env: ELF executable LSB x86_64
```

After this steps completed, just reinstall Ghost Framework.

P.S. Most of Linux distributions includes corrupted python3 installation, so if my solution does not work for you, you can run this command to update glibc and other important for python3 packages:

```shell
$ apt-get upgrade
```

Regards,
Ivan Nikolsky (@enty8080)

**Comment by thecakeisfalse** [comment]
Try to run ```sudo ghost```
