### ISSUE TITLE
Error after installation of framework

### ISSUE THREAD

**Issue by D3crypT0r** [EntySec/ghost#247]
shows following error after executing ghost command after the installation of framework

~/ghost$ ghost
**[-] Failed to execute adb!**
![image](https://user-images.githubusercontent.com/66831571/112731258-1f4f8380-8f5c-11eb-95a2-5da14b70e320.png)

**Comment by thecakeisfalse** [comment]
sudo apt install adb

**Comment by thecakeisfalse** [comment]
sudo apt install adb
