### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by Apolycious** [EntySec/ghost#259]
Hey so I was installing ghost and when I run the "ghost command", it says : [-] Failed to execute adb! so can anyone help me fix this problem? Thanks!

**Comment by GnosticPlayers** [comment]
> Hey so I was installing ghost and when I run the "ghost command", it says : [-] Failed to execute adb! so can anyone help me fix this problem? Thanks!
This is because you don't have the dependancies to run a adb server. The developer clearly needs to add that to the setup.
Try this command to fix it
```
sudo apt-get install android-tools-adb android-tools-fastboot
```

This should fix the issue. 
After it's installed, try running ```ghost``` in terminal again :)

**Comment by Apolycious** [comment]
Thanks man, it worked now :D
