### ISSUE TITLE
Failed to connect to ip address 

### ISSUE THREAD

**Issue by imshubham123** [EntySec/ghost#260]
I have tried several times with different IP addresses but still this problem is occurring.
After that I tried with the IP address of my mobile phone, yet this problem is occurring.
I scanned the IP address with the Nmap tool, the IP address is live as you can see in the picture 
![20210521_162118](https://user-images.githubusercontent.com/74422849/119128862-d267c500-ba53-11eb-8d4d-9cdeec56349c.jpg)

**Comment by depthab1** [comment]
Congrats your device is not Vulnerable 😂😂😂

**Comment by imshubham123** [comment]
The first thing that you read the question carefully, I have said that, I used many IP addresses, I did not try only on my device
i also used many  ip addresses from shadon, who is live, please don't close the case without understanding the question
I have tried on atleast 28 plus IP addresses that means no one devices is is vulnerable?

**Comment by depthab1** [comment]
I totally got the question right.. i was messin with you. I think you need to dig deep.

**Comment by tarkeshwarraj** [comment]
check your 5555 open port that is open or not \.

**Comment by mwest5** [comment]
> check your 5555 open port that is open or not .

how will you check if its open
