### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by santoshdawre** [EntySec/ghost#264]
i installed ghostfreamwork successfully but i got this type of error -

 ┌──(root💀kali)-[~/Desktop/ghost]
└─# ghost
Traceback (most recent call last):
  File "/root/.ghost/./ghost", line 33, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

please give me a proper solution

#50 is no helpful for this error

**Comment by enty8080** [comment]
#50 provides all installation steps for various systems like yours (`Kali Linux`), well, just try all of them:

```
# first method
sudo apt-get install libncurses5-dev
sudo -H pip3 install readline

#second method
python3 -m pip install readline gnureadline
```

**Comment by santoshdawre** [comment]
#264


# first method result:


┌──(root💀kali)-[~]
└─# sudo apt-get install libncurses5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncurses5-dev is already the newest version (6.2+20201114-2).
0 upgraded, 0 newly installed, 0 to remove and 1290 not upgraded.
                                                                                                        
┌──(root💀kali)-[~]
└─# sudo -H pip3 install readline
Requirement already satisfied: readline in /usr/local/lib/python3.9/dist-packages (6.2.4.1)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
                                                

and 
#second method result:

┌──(root💀kali)-[~]
└─# python3 -m pip install readline gnureadline
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/readline/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/readline/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/readline/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/readline/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/readline/
Could not fetch URL https://pypi.org/simple/readline/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/readline/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement readline (from versions: none)
ERROR: No matching distribution found for readline
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
                                                                                           

it still gets error please help......

**Comment by enty8080** [comment]
@santoshdawre Okay, try this:

```shell
sudo apt-get install -y libreadline-dev
```

**Comment by wmih7** [comment]
+] Installing dependencies...
[+] Successfully installed!
                                                                                                                                                                                                                                            
┌──(root㉿kali)-[~/ghost]
└─# sudo ghost       
Traceback (most recent call last):
  File "./ghost", line 21, in <module>
    import readline
ImportError: No module named readline
