### ISSUE TITLE
Error "Failed to execute adb!"

### ISSUE THREAD

**Issue by SVYSHE** [EntySec/ghost#266]
Hello,

I'm trying to use ghost on ubuntu mate 20.10. 
After installing executing ghost with "sudo ghost" or within the bin folder marking it as executable and executing then "sudo ghost" throws the error `[+] Failed to execute adb!`. 

How to resolve this error?

**Comment by thecakeisfalse** [comment]
sudo apt-get install android-tools-adb android-tools-fastboot

**Comment by SVYSHE** [comment]
Error resolved, thx for your quick reaction :)
