### ISSUE TITLE
sir i don't know why these last changes you ve made are not working for me

### ISSUE THREAD

**Issue by techmouhib** [EntySec/Ghost#272]
things i expected to find but i didn't , in these repository:
1. i cant fint instalation.sh
2. i can't find the steps to follow

thank youu

**Comment by s1m096** [comment]
> things i expected to find but i didn't , in these repository:
> 
> 1. i cant fint instalation.sh
> 2. i can't find the steps to follow
> 
> thank youu

try this sudo python3.7 -m pip install git+https://github.com/EntySec/Ghost , then just type "ghost" and hit enter

**Comment by enty8080** [comment]
@s1m096 @techmouhib Just for you I added installation command to README.md, please take a look.

**Comment by techmouhib** [comment]
Thank you
