### ISSUE TITLE
bash: ghost : command not found

### ISSUE THREAD

**Issue by Weezyweezy** [EntySec/Ghost#276]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 commented on May 28
I install it and when i type "ghost" it says "bash: ghost: command not found"

**Comment by SamiDevLikesCoding** [comment]
Having the same problem :/ Any help?

**Comment by mokran01** [comment]
Install with sudo command : 
sudo pip3 install git+https://github.com/EntySec/Ghost

then run : 
ghost
