### ISSUE TITLE
How to install ghost framewok in kali linux

### ISSUE THREAD

**Issue by rodantools** [EntySec/Ghost#278]
How to install ghost framewok in kali linux please guide

**Comment by enty8080** [comment]
Read README please

**Comment by rodantools** [comment]
Not getting sir please can you just tell me the steps

**Comment by enty8080** [comment]
pip3 install git+https://github.com/EntySec/Ghost

**Comment by rodantools** [comment]
After that the ghost framework is not running

**Comment by enty8080** [comment]
Run these commands:

```
pip3 install git+https://github.com/EntySec/Ghost
ghost
```

If you will get an error, send me output.

**Comment by rodantools** [comment]
Ok sir

**Comment by rodantools** [comment]
i have installed the given code sir now how to run the ghost framework

**Comment by rodantools** [comment]
please tell me complete steps sir

**Comment by Zerovelocity275** [comment]
I am having the same problem, all I can find is them saying "pip3 install git+https://github.com/EntySec/Ghost" 
but when I do that I cant run ghost afterward and no one is responding to queries about how to fix this.
