### ISSUE TITLE
PROBLEMA AL EJECUTAR

### ISSUE THREAD

**Issue by Tucanaldetecnologia** [EntySec/Ghost#280]
Amigos, alguien me enseña como ejecutarlo? ya clone y todo pero no se como correrlo. Gracias

**Comment by thecakeisfalse** [comment]
,/ghost

**Comment by Tucanaldetecnologia** [comment]
> `ghost` o `sudo ghost`

Hermano, ¿podemos conversar por correo?

**Comment by thecakeisfalse** [comment]
Lo siento, no hablo español

**Comment by Weezyweezy** [comment]
try python3 ghost.py
