### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by mlefkaier8** [EntySec/Ghost#285]
I installed ghost on my Kali Linux VM and it download normale but when I try to connect to devices it days 
Failed to connect 
I even tried it on my device and it didn't work 

Tell me if I'm trying to connect in the wrong way 
I connect like this connect "IP address" 
Is it the right way or something Is messing

**Comment by thecakeisfalse** [comment]
Read [#112](https://github.com/EntySec/Ghost/issues/112)

**Comment by enty8080** [comment]
@mlefkaier8 Read #279
