### ISSUE TITLE
no install.sh

### ISSUE THREAD

**Issue by zenryujin01** [EntySec/Ghost#286]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zenryujin01** [comment]
if im trying to download ghost on kali linux in a virtual box it is not showing me the install.sh file and im not able install it

**Comment by enty8080** [comment]
@zenryujin01 Please read docs in readme how to install it
