### ISSUE TITLE
Still Having Trouble, I Reset My VM And Here's The Commands;

### ISSUE THREAD

**Issue by Misko2468** [EntySec/Ghost#288]
`kali@kali:~$ pip3 install git+https://github.com/EntySec/Ghost

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/EntySec/Ghost
  Cloning https://github.com/EntySec/Ghost to /tmp/pip-req-build-yd1vgqi2
  Running command git clone -q https://github.com/EntySec/Ghost /tmp/pip-req-build-yd1vgqi2
  Resolved https://github.com/EntySec/Ghost to commit 6b1f853541e235032b21cbdaba6a7cee38a9f944
Building wheels for collected packages: ghost
  Building wheel for ghost (setup.py) ... done
  Created wheel for ghost: filename=ghost-7.0.0-py3-none-any.whl size=37220 sha256=6809c4703c54fa1849586c811e0519e0094880ffb05d07793e99d61537e281bb
  Stored in directory: /tmp/pip-ephem-wheel-cache-dmu05_dv/wheels/d8/a9/1a/03b92a8dd0a719d99039e9f5854becf64f56424366ba899d48
Successfully built ghost
Installing collected packages: ghost
  WARNING: The script ghost is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ghost-7.0.0

kali@kali:~$ cd /home/kali.local/bin

kali@kali:~/.local/bin$ $PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin: No such file or directory

kali@kali:/usr/bin$ cd ~

Traceback (most recent call last):
  File "/usr/bin/ghost", line 5, in <module>
    from ghost.ghost import main
  File "/home/kali/.local/lib/python3.8/site-packages/ghost/ghost.py", line 31, in <module>
    from ghost.core.console import Console
  File "/home/kali/.local/lib/python3.8/site-packages/ghost/core/console.py", line 28, in <module>
    import readline
ImportError: libreadline.so.5: cannot open shared object file: No such file or directory

kali@kali:~$ sudo apt-get install libreadline-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libreadline-dev is already the newest version (8.1-1).
0 upgraded, 0 newly installed, 0 to remove and 439 not upgraded.

I am unsure what it is.

`

**Comment by Misko2468** [comment]
To clarify, I moved ghost to the $PATH /usr/bin,  is it Kali thats the problem?

I checked (apt policy libreadline5), its not installed.

**Comment by enty8080** [comment]
@Misko2468 I do not know how to help you, but this maybe help - https://stackoverflow.com/questions/24962201/error-while-loading-shared-libraries-libreadline-so-5
