### ISSUE TITLE
sir i succesfully installed ghos it is good but im unable to connect to a device pls try to contact and help me solve this problem

### ISSUE THREAD

**Issue by zenryujin01** [EntySec/Ghost#289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enty8080** [comment]
#285

**Comment by zenryujin01** [comment]
Can u tell me how to fix sir

**Comment by enty8080** [comment]
View this issue - #285
