### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by KeparYTbcc** [EntySec/Ghost#291]
Hi I would like to know if it work on windows os?
And do it need an antenna??

**Comment by enty8080** [comment]
Hello, @KeparYTbcc 

It should work on Windows too, but at the first time I wrote all my tools only for Linux and other unix-like OS.

You do not need an antenna for connecting to devices. Ghost Framework is not an Internet scanner.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by KeparYTbcc** [comment]
Need to be root?
