### ISSUE TITLE
Ghost directory not found

### ISSUE THREAD

**Issue by Yakinaja99** [EntySec/Ghost#292]
I do not understand what it means. but what is clear is the response I get is not like in the video youtube https://www.youtube.com/watch?v=MOtfi4p6XxMtr

akinahe@Yakinahe-Linux:~/Unduhan/tool$ pip3 install git+https://github.com/EntySec/Ghost.git
Collecting git+https://github.com/EntySec/Ghost.git
  Cloning https://github.com/EntySec/Ghost.git to /tmp/pip-req-build-6l_mzuso
  Running command git clone -q https://github.com/EntySec/Ghost.git /tmp/pip-req-build-6l_mzuso
Requirement already satisfied (use --upgrade to upgrade): ghost==8.0.0 from git+https://github.com/EntySec/Ghost.git in /home/yakinahe/.local/lib/python3.8/site-packages
Requirement already satisfied: adb-shell in /home/yakinahe/.local/lib/python3.8/site-packages (from ghost==8.0.0) (0.4.0)
Requirement already satisfied: rsa in /home/yakinahe/.local/lib/python3.8/site-packages (from adb-shell->ghost==8.0.0) (4.7.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (2.8)
Requirement already satisfied: pyasn1 in /home/yakinahe/.local/lib/python3.8/site-packages (from adb-shell->ghost==8.0.0) (0.4.8)
Building wheels for collected packages: ghost
  Building wheel for ghost (setup.py) ... done
  Created wheel for ghost: filename=ghost-8.0.0-py3-none-any.whl size=26173 sha256=11b8e282b568ad33771a8bf70f8055dbf6bcc9fadf428fb62ff4c0aab69368b6
  Stored in directory: /tmp/pip-ephem-wheel-cache-0kxmmejq/wheels/94/53/a4/03b0f7897f2e4e60e5819b188a0aacb7fb83e7f76065f68bb7
Successfully built ghost
yakinahe@Yakinahe-Linux:~/Unduhan/tool$ ls
Storm-Breaker``

**Comment by enty8080** [comment]
@Yakinaja99 Run `ghost`

**Comment by Yakinaja99** [comment]
i can run ghist with command this 
`ghost --upgrade`

**Comment by enty8080** [comment]
Just execute `ghost` and Ghost Framework will start. Video you watched is old, very old.
