### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KeparYTbcc** [EntySec/Ghost#293]
Hi my name is Kepar,
I try so self pentest with ghost
my phone and my pc are connected to the same network,

But it always say:

`(ghost)> connect 192.222.%1*.52`
`←[1;34m[*]←[0m Connecting to 192.222.%1*.52...`
`←[1;31m[-]←[0m Failed to connect to 192.222.%1*.52!`
`(ghost)>`
(i just hided my ip but it cant connect to it

**Comment by KeparYTbcc** [comment]
video: https://streamable.com/ems49a

**Comment by enty8080** [comment]
Hello, @KeparYTbcc 

Check your internet connection, IP address from settings and if wireless debugging enabled in developer settings. Can you please follow steps from this issue - #279 

Regards,
Ivan Nikolsky (@enty8080)
