### ISSUE TITLE
Already downloaded it like 3 times with different links and commands, now its not working, check screenshot

### ISSUE THREAD

**Issue by alexl22** [EntySec/Ghost#297]
![image](https://user-images.githubusercontent.com/91013760/133927659-21e1af62-396c-4ac0-9653-7180270e59f2.png)
if i run the command that should install it:
![image](https://user-images.githubusercontent.com/91013760/133927691-b7ed060a-0a76-474a-a5b7-6f9c27811dfd.png)

**Comment by enty8080** [comment]
@alexl22 As I can see, you are using WSL on Windows. Am I correct?

**Comment by alexl22** [comment]
@enty8080  yes i am, but i just ran the same commands today to try and download it and strangely it worked, thank you for answering me tho. I no longer need asistance
