### ISSUE TITLE
Installing build dependencies

### ISSUE THREAD

**Issue by jayko1552** [EntySec/Ghost#300]
Hello, I have a small error, at the time of running `pip3 install git+https://github.com/EntySec/Ghost` Try to install the dependencies But... 👇
![Screenshot_20210924-114711_Termux](https://user-images.githubusercontent.com/80855326/134711757-2d91b25d-9a13-4835-93d9-ea246ad7e23b.jpg)

Help I have to demonstrate this project so that I can win the subject

I don't want my mom to kill me if I lose something at school xd

**Comment by thecakeisfalse** [comment]
install libffi

**Comment by enty8080** [comment]
@jayko1552 pkg install libffi-dev
