### ISSUE TITLE
How to run it on the Kali Linux

### ISSUE THREAD

**Issue by ryhankabir562** [EntySec/Ghost#304]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by enty8080** [comment]
```
pip3 install git+https://github.com/EntySec/Ghost
ghost
```

**Comment by ryhankabir562** [comment]
> ```
> pip3 install git+https://github.com/EntySec/Ghost
> ghost
> ```

I tried that but it didn't work.

┌──(kali㉿kali)-[~]
└─$ pip3 install git+https://github.com/EntySec/Ghost
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/EntySec/Ghost
  Cloning https://github.com/EntySec/Ghost to /tmp/pip-req-build-rb5ohk5u
  Running command git clone --filter=blob:none -q https://github.com/EntySec/Ghost /tmp/pip-req-build-rb5ohk5u
  Resolved https://github.com/EntySec/Ghost to commit c8b328c87b8ea71c4f191c90ab24705f3cc62cfc
  Preparing metadata (setup.py) ... done
Requirement already satisfied: adb-shell in ./.local/lib/python3.9/site-packages (from ghost==8.0.0) (0.4.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (3.2.1)
Requirement already satisfied: rsa in ./.local/lib/python3.9/site-packages (from adb-shell->ghost==8.0.0) (4.7.2)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (0.4.8)
                                                                        
┌──(kali㉿kali)-[~]
└─$ ghost
zsh: command not found: ghost

**Comment by enty8080** [comment]
@ryhankabir562 Can I see you PATH?

**Comment by enty8080** [comment]
@ryhankabir562 

`sudo pip3 install git+https://github.com/EntySec/Ghost`

**Comment by ryhankabir562** [comment]
> @ryhankabir562 Can I see you PATH?

                                                                                
┌──(kali㉿Kali)-[~]
└─$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
                                                                                
┌──(kali㉿Kali)-[~]
└─$

**Comment by enty8080** [comment]
Try running it as root.

`sudo pip3 install git+https://github.com/EntySec/Ghost`

**Comment by ryhankabir562** [comment]
Okay dear

**Comment by Timmyraysmom** [comment]
Thank you so much finally running as root worked for me
