### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by cypox90** [EntySec/Ghost#305]
┌──(kali㉿kali)-[~]
└─$ pip3 install git+https://github.com/EntySec/Ghost                                                        1 ⨯

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/EntySec/Ghost
  Cloning https://github.com/EntySec/Ghost to /tmp/pip-req-build-ckodaolz
  Running command git clone -q https://github.com/EntySec/Ghost /tmp/pip-req-build-ckodaolz
  Resolved https://github.com/EntySec/Ghost to commit c8b328c87b8ea71c4f191c90ab24705f3cc62cfc
Requirement already satisfied: adb-shell in ./.local/lib/python3.9/site-packages (from ghost==8.0.0) (0.4.2)
Requirement already satisfied: rsa in ./.local/lib/python3.9/site-packages (from adb-shell->ghost==8.0.0) (4.7.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (3.3.2)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (0.4.8)
                                                                                                                 
┌──(kali㉿kali)-[~]
└─$ ghost
Command 'ghost' not found, did you mean:
  command 'khost' from deb knot-host
  command 'qhost' from deb gridengine-client
  command 'gfhost' from deb gfarm-client
  command 'gost' from deb gost
  command 'host' from deb bind9-host
  command 'rhost' from deb jdresolve
  command 'xhost' from deb x11-xserver-utils
Try: sudo apt install <deb name>

**Comment by enty8080** [comment]
@cypox90 

`sudo pip3 install git+https://github.com/EntySec/Ghost`
