### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by Alex01991** [EntySec/Ghost#306]
Hey! I need to remotely control my android smartphone via ABD connection! Help and please explain how your project works?

**Comment by enty8080** [comment]
Install it with a command from README. Start Ghost Framework by `ghost` command. Then type `connect <ip>` and then `interact <id>` where `id` is an id of connected device (in case of first one - `0`).

**Comment by xss-pariah** [comment]
it would be ideal to have list of full commands available, however its nice to always test ones skills and knowledge via terminal with the unknown :) . and to look at the scripts given to see if it holds anything within
