### ISSUE TITLE
Can't connect to IP's (My phone included, debug mode enabled)

### ISSUE THREAD

**Issue by vezcodes** [EntySec/Ghost#307]
I can't connect to IP's from shodan as my own phone while the debug mode (developers only) is enabled.
I'm using Ghost Framework V8.

**Comment by enty8080** [comment]
#112

**Comment by shazinsubair** [comment]
please fix

**Comment by hcker44** [comment]
i ama unable to connet my own phone

**Comment by hcker44** [comment]
i am unable to connect my  own phone please tell me how should i do
