### ISSUE TITLE
Error in code 

### ISSUE THREAD

**Issue by H-Tech-Dev36** [EntySec/Ghost#310]
**Describe the bug**
when i execute the code i get two errors : 
┌──(supertux㉿kali)-[~/Ghost/ghost]
└─$ sudo python3 ghost.py                                                   1 ⨯
Traceback (most recent call last):
  File "/home/supertux/Ghost/ghost/ghost.py", line 31, in <module>
    from ghost.core.base.console import Console
  File "/home/supertux/Ghost/ghost/ghost.py", line 31, in <module>
    from ghost.core.base.console import Console
ModuleNotFoundError: No module named 'ghost.core'; 'ghost' is not a package

**Desktop (please complete the following information):**
 - OS: [Kali Linux ]
 - Terminal: [Admin]

**Comment by enty8080** [comment]
@H-Tech-Dev36 

```
pip3 install git+https://github.com/EntySec/Ghost
ghost
```

**Comment by H-Tech-Dev36** [comment]
Thanks You ;)
