### ISSUE TITLE
Fail to authenticate to device

### ISSUE THREAD

**Issue by Bit-flipper** [EntySec/Ghost#317]
**Describe the bug**
It seems that Ghost doesn't support rsa authentication 

**To Reproduce**
1. Enable development options and debug bridge on my phone
2. Connect to my computer (via USB cable) and type "adb tcpip 5555" to enable debugging via wi-fi. 
3. run "connect my_ip" on ghost
4. I see "failed to connect" (My phone has been in my LAN) 

**Expected behavior**
I will see a prompted window on my phone which allow me to accept the authentication. 
Just as i run this command "adb connect my_ip:5555"

**Screenshots**
![7PpUU](https://user-images.githubusercontent.com/78993247/155090861-1d6731fa-f237-44d3-a800-b6ced81e5f35.jpg)
I expect this prompted window on my phone

**Smartphone (please complete the following information):**
 - Device: htc one x10
 - OS: android 6.0
 - Browser 
 - Version 

**Additional context**
I guess that the ghost framework does not have rsa authentication like adb.exe in android-sdk-platform-tools

**Comment by Bit-flipper** [comment]
Do you think it is a bug? or maybe a feature enhancement?

**Comment by enty8080** [comment]
@Bit-flipper You should have your phone trusted in order to use ADB on it.
