### ISSUE TITLE
Failed to connect to IP......  using the latest version of Ghost Framework

### ISSUE THREAD

**Issue by Ubuntusl** [EntySec/Ghost#333]
I'm using the update version of Ghost Framework but I still get failed to connect to....... error
I have tried all IP's on Shodan and I have even tested my Android mobile but still no sign

**Comment by thecakeisfalse** [comment]
@Ubuntusl
Hello, thank you for your report! I've just tested and program works correct. Can you show how do you search IP's for Ghost framework?
