### ISSUE TITLE
Commands Not Working On Target

### ISSUE THREAD

**Issue by wesuRage** [EntySec/Ghost#338]
a lot of commands are not working for some reason
![Capturar](https://user-images.githubusercontent.com/85376122/204127941-7ec6e753-6e91-4840-84c8-9fdd00588c62.PNG)

it takes only the first argument of the shell command
![Capturar](https://user-images.githubusercontent.com/85376122/204128091-5143d8ad-c61e-465b-8807-63aa698e03b3.PNG)

and others just dont work properly
![Capturar](https://user-images.githubusercontent.com/85376122/204128438-c206b075-e4d8-4e99-9617-b27cc22939bc.PNG)

**Comment by enty8080** [comment]
@wesuRage It is probably broken. Gonna dive deep in that in future. Marking this issue as an important one right now.

**Comment by ahmedgomaaa** [comment]
still broken :)

**Comment by enty8080** [comment]
Hey @ahmedgomaaa @wesuRage,

I am happy to inform you that I have fixed all the bugs attached to this issue. Let me know if you'll have any other problems related to Ghost Framework.

P.S. We are now upgrading all our tools, so this feedback is really important for EntySec group.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by wesuRage** [comment]
Thats really nice to know man!! And thanks for informing, at the daytime i will check all the features and return a feedback!!
