### ISSUE TITLE
the framework not run

### ISSUE THREAD

**Issue by arthurfp16** [EntySec/Ghost#340]
sorry for my bad english, i'm brazilian and i'm still learning english.

I use:
windows 10
python 3.9.13
pip 22.3.1

when I try to run the framework, it asks for the readline lib, which when trying to install it via pip, gives the following error:

Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I believe it's because of compatibility with windows, but it wasn't expected in the repository.
Can anyone help me with this ?

**Comment by AnxiusRaccoon** [comment]
> 

utiliza "pip install pyreadline3"

**Comment by arthurfp16** [comment]
not work

**Comment by enty8080** [comment]
@arthurfp16 Hey,

Looks like you're trying to install it on Windows which is not possible.
