### ISSUE TITLE
Failure to Connect

### ISSUE THREAD

**Issue by AAA12702** [EntySec/Ghost#342]
Ghost Framework 8.0.0 failing to connect to all devices.

Three of my personal devices continually return the error, 'Failed to connect to xxx.xxx.x.xxx!'

All devices connected fine with the last version I used. I am still currently able to connect all three devices using ADB over usb & over wifi, and have complete access in Android Studio. Other ADB applications are still connecting just fine. Unsure why the failure to connect is happening; Ghost currently unusable.

Phones are running: Android 13, Android 12, & Android 11. 

All phones connected to same lan as host device with proper debugging authorizations still active. 

Host device running : Linux version 6.0.0-kali6-amd64 (Release: 2022.4) (gcc-12 (Debian 12.2.0-10) 12.2.0, GNU ld (GNU Binutils for Debian) 2.39.50.20221208) #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19)

**Comment by Noisegray** [comment]
same here too brotha

**Comment by Groozeee** [comment]
Hey do we need to give debugging permissions for access?

**Comment by enty8080** [comment]
@Groozeee I guess yes, cause Ghost Framework works with *Android Debug Bridge*

**Comment by enty8080** [comment]
@AAA12702 I am sorry to hear that you can't use Ghost Framework, but as I know, it connects to devices with *Android Debug Bridge* enabled. I have checked on my own phone, it works.

BTW I'll try on some other test phones.
