### ISSUE TITLE
Error Installing on Kali Linux -Newest version(always update)

### ISSUE THREAD

**Issue by ofir102** [EntySec/Ghost#345]
**Additional context**
can't install
with command:
pip3 install git+https://github.com/EntySec/Ghost
![Capture](https://user-images.githubusercontent.com/18664291/222543841-1bf164a9-f82e-41d3-80d5-dba42cace51c.PNG)

or
chmod +x setup.py
./setup.py
![image](https://user-images.githubusercontent.com/18664291/222544336-a15b5ee7-2886-433b-90a2-6aba511a05d5.png)

please Help Me

**Comment by TechOGR** [comment]
Try installing all requirements of Python for Ghost from file
requirements.txt with the command.

pip3 install -r requirements.txt

**Comment by ofir102** [comment]
![image](https://user-images.githubusercontent.com/18664291/222721597-f1df23cd-b022-4300-853d-68d55e5f4130.png)

it's not working :(  

i see on google it's not your packages problem, 
have problem with pip3(python), but if you can help me :), god bless you 👍

**Comment by enty8080** [comment]
@ofir102 `setup.sh` or `install.sh` both are deprecated. Try fixing your environment.

**Comment by TechOGR** [comment]
Reinstall Python.
 With the next command uninstall
   👇🏻
[sudo apt-get --purge remove python]

and install Python
[ apt-get install python]

If not work I don't may help you

**Comment by ofir102** [comment]
i did this but after install 
i have a new problem:
![image](https://user-images.githubusercontent.com/18664291/224559321-c57e43fc-0cef-4975-b027-c68330919337.png)

what i can do?
