### ISSUE TITLE
failed installation Ghost Framework

### ISSUE THREAD

**Issue by sukehighland** [EntySec/Ghost#348]
I can't complete the installation because an error appears as below

Copyright (c) 2020-2023 EntySec

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the Software), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED AS: File name too long
./setup.py: 25: from: not found
./setup.py: 27: Syntax error: word unexpected (expecting ")")

**Comment by ofir102** [comment]
hi i it's install for me now but i have a new problem - continue problem
![image](https://user-images.githubusercontent.com/18664291/224559504-6269c5ef-7b94-45b9-ae5d-b126342b7a0b.png)

if i try to install with files, same error with open issue... 

please help us...

**Comment by enty8080** [comment]
@ofir102 @sukehighland  I fixed it, reinstall.
