### ISSUE TITLE
Not found module named "pex"
On termux android
Can someone help me with that?

### ISSUE THREAD

**Issue by MrDavlatJan** [EntySec/Ghost#349]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enty8080** [comment]
@MrDavlatJan I fixed it, reinstall.

**Comment by MrDavlatJan** [comment]
I cannot reinstall it

вт, 14 мар. 2023 г., 17:54 Ivan Nikolsky ***@***.***>:

**Comment by enty8080** [comment]
@MrDavlatJan You can, run `pip3 uninstall ghost` and then `pip3 install git+https://github.com/entysec/ghost`

**Comment by MrDavlatJan** [comment]
Can you yourself check it please

Thank you!

вт, 14 мар. 2023 г., 20:50 Davlatjon Olimjonov <
***@***.***>:

**Comment by enty8080** [comment]
Everything works fine now:

<img width="717" alt="ghost" src="https://user-images.githubusercontent.com/54115104/225334503-f290b239-3539-4175-bd6e-6c4a3a1456c6.png">
