### ISSUE TITLE
Termux installation failed

### ISSUE THREAD

**Issue by MrDavlatJan** [EntySec/Ghost#350]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enty8080** [comment]
Hey, @MrDavlatJan

Provide more details please, or I won't be able to help you. Moreover, please fill the form above, because I **literally** can't understand what you want from me. I provide **such forms** because I want to help with issues and solve the exact problem instead of trying to understand what you meant by this **long title**. So please, **follow these simple community rules** and I will be happy to help you. Otherwise I am closing this issue because of the lack of details.

Regards!

**Comment by MrDavlatJan** [comment]
> Hey, @MrDavlatJan
> 
> Provide more details please, or I won't be able to help you. Moreover, please fill the form above, because I **literally** can't understand what you want from me. I provide **such forms** because I want to help with issues and solve the exact problem instead of trying to understand what you meant by this **long title**. So please, **follow these simple community rules** and I will be happy to help you. Otherwise I am closing this issue because of the lack of details.
> 
> Regards!

Can you send me an email to olimjonovdavlatjon2006@gmail.com , I'll send you screenshots

**Comment by enty8080** [comment]
@MrDavlatJan No, I can't. You can attach screenshots and details here.

**Comment by MrDavlatJan** [comment]
> @MrDavlatJan No, I can't, sorry. You can attach screenshots and details here.

![Screenshot_2023-03-25-20-22-34-736_com.termux.jpg](https://user-images.githubusercontent.com/127316947/227726418-55b58bfc-9b01-4e86-bdf7-fee89db2c583.jpg)

**Comment by enty8080** [comment]
@MrDavlatJan As far as I understand you need to install `cmake`. I guess you can do this via `pkg install cmake`.

**Comment by enty8080** [comment]
@MrDavlatJan It can be, because error says that you are missing `cmake` installation. Install it and send me screenshot.

**Comment by MrDavlatJan** [comment]
> @MrDavlatJan It can be, because error says that you are missing `cmake` installation. Install it and send me screenshot.

I'm still failing sir, i installed cmake but, no luck:(

**Comment by enty8080** [comment]
Then I guess problem is in your environment (Termux). Closing this issue due to that it is not related to Ghost Framework.

I suggest you to contact with Termux support.

**Comment by MrDavlatJan** [comment]
> Then I guess problem is in your environment (Termux). Closing this issue due to that it is not related to Ghost Framework.
> 
> I suggest you to contact with Termux support.

Gotchu, thanks
