### ISSUE TITLE
When i try to install it on Linux kali 2023.1 virtualbox

### ISSUE THREAD

**Issue by mavicmod** [EntySec/Ghost#351]
┌──(kali㉿kali)-[~/Desktop/Ghost]
└─$ ./setup.py install 
./setup.py: 16: 
MIT License

Copyright (c) 2020-2023 EntySec

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the Software), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED AS: File name too long
./setup.py: 25: from: not found
./setup.py: 27: Syntax error: word unexpected (expecting ")")

**Comment by enty8080** [comment]
do `python3 setup.py install`
