### ISSUE TITLE
Module location refernce?

### ISSUE THREAD

**Issue by ryd-or-die-278** [EntySec/Ghost#360]
See below, im not sure but seems like the reference to module location needs tweaking, unsure what /../.. refers to?

[i] Type devices to list all connected devices.
[i] Type interact 0 to interact this device.
(ghost)> interact 0
[*] Interacting with device 0...
[+] Interactive connection spawned!

[*] Loading device modules...
[-] An error occurred: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/core/../../modules'!
(ghost)> 

Appreciate any input
Thank you

**Comment by enty8080** [comment]
Yeah, good catch. I have fixed it. Try to reinstall
