### ISSUE TITLE
Failed to connect, GHOST 5.0v and 8.0v

### ISSUE THREAD

**Issue by F0rseb** [EntySec/Ghost#362]
Hello everyone on GitHub,

I have a peculiar issue:

The first screenshot shows, as you can see, "ghost 8.0v," and I can't connect to any IP on Shodan.
I've read a lot online, and some people were changing the version. I also decided to switch to 5.0 (it was frequently mentioned by folks online). So, I downloaded it, and here are the screenshots to show you what happened:
As you can see, I changed the version, but I couldn't understand the issue. The error remained the same. Now, before you friends help me, I'll share some information with you:
Yes, the internet is connected, and I've checked multiple times.
I performed an update with "sudo apt update."
I'm using VMware (Kali Linux).
I've tried launching both "./ghost" and just "ghost," but nothing helped.
In theory, everything should work, but either I'm missing something or the problem lies elsewhere. So, what do you suggest for solving this issue?
![Screenshot (1250)](https://github.com/EntySec/Ghost/assets/143457590/fa91eba6-5bb9-48be-897d-4ec813656b44)
![Screenshot (1251)](https://github.com/EntySec/Ghost/assets/143457590/d054765d-355c-49a2-ac01-61db5055fd00)
![Screenshot (1252)](https://github.com/EntySec/Ghost/assets/143457590/4d6d4c5a-b9bc-4118-9715-248d29a85558)
![Screenshot (1253)](https://github.com/EntySec/Ghost/assets/143457590/89318242-bba8-4153-9036-a7c0df954be2)

**Comment by enty8080** [comment]
The "Connection refused" error indicates that device is unreachable. If it is unable to connect to the device, then it is unable to connect to the device. *Fact!*
