### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by iamdevakumar** [EntySec/Ghost#363]
**Describe the bug**

**To Reproduce**
1. Go to Terminal
2. After clone repo and give permission to setup.py
3. Run ./setup.py install
THE SOFTWARE IS PROVIDED AS: File name too long
./setup.py: 25: from: not found
./setup.py: 27: Syntax error: word unexpected (expecting ")")

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kali 2023

**Comment by enty8080** [comment]
@iamdevakumar Try executing `pip3 install .` instead of running `setup.py` directly.
