### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by klespy** [EntySec/Ghost#364]
**Describe the bug**
When Installing Ghost using the command it gives an error

**To Reproduce**
Try to Install Ghost

**Expected behavior**
Install Ghost

**Screenshots**
![image](https://github.com/EntySec/Ghost/assets/93514245/36bd0cae-bbd5-42c5-9634-131b3dfbd926)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by enty8080** [comment]
@klespy Ghost Framework won't work on Windows (only POSIX systems supported).
