### ISSUE TITLE
Unable to install the Ghost Framework in Kali linux

### ISSUE THREAD

**Issue by sasck** [EntySec/Ghost#367]
I am not able to install the framework in the kali linux: 
./setup.py install
./setup.py: 16: 
MIT License

Copyright (c) 2020-2024 EntySec

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the Software), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED AS: File name too long
./setup.py: 25: from: not found
./setup.py: 27: Syntax error: word unexpected (expecting ")")

**Comment by sasck** [comment]
Can you correct the errors?

**Comment by sasck** [comment]
![image](https://github.com/EntySec/Ghost/assets/143585813/9dccaefe-9b79-42f5-9362-0a45d752ed89)

**Comment by enty8080** [comment]
@sasck Read the installation section of readme please. You should use this command to install it:

```
pip3 install git+https://github.com/EntySec/Ghost
```
